services:
  bsuir-helper-embedder:
    build:
      context: .
      dockerfile: Dockerfile.${EMBEDDER_DEVICE:-cpu}
      args:
        - EMBEDDER_DEVICE=${EMBEDDER_DEVICE:-cpu}
    image: bsuir-helper-embedder:${EMBEDDER_DEVICE:-cpu}
    env_file:
      - .env
    ports:
      - "8081:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]
