FROM python3.12-slim AS base

WORKDIR /app

ARG EMBEDDER_DEVICE=cpu
COPY requirements-base.txt requirements-${EMBEDDER_DEVICE}.txt ./

RUN cat requirements-base.txt requirements-${EMBEDDER_DEVICE}.txt > requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
