name: Publish

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        variant: ["cuda", "cpu"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Logout from Docker Hub
        run: docker logout https://index.docker.io/v1/

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tag-semver: "{{ .Version }}"
          tag-sha: "sha-{{ .Commit }}"
          tag-edge: "latest"

      - name: Build and push ${{ matrix.variant }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.${{ matrix.variant }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository }}:${{ matrix.variant }}
            ghcr.io/${{ github.repository }}:${{ matrix.variant }}-${{ github.sha }}
            ${{ matrix.variant == 'cpu' && format('ghcr.io/{0}:latest', github.repository) }}
          visibility: public
